/**
 * KISOK Android release-signing Expo config plugin.
 *
 * Env-guarded, fail-closed, idempotent signing configuration for CNG (the
 * android/ tree is regenerated by `expo prebuild` and never committed, so
 * upload-signing material reaches it only through this plugin):
 *
 * - WITH all four MYAPP_UPLOAD_* env vars present at prebuild time:
 *   writes the four upload-signing entries into android/gradle.properties
 *   and adds the documented Expo/RN `hasProperty`-guarded
 *   `signingConfigs.release` block to android/app/build.gradle, pointing
 *   buildTypes.release at it so the release variant actually uses it.
 *   https://reactnative.dev/docs/signed-apk-android
 * - WITHOUT them (any of the four absent — partial counts as absent): the
 *   plugin performs NO modification of either file. The Expo template's
 *   debug-signed release variant is preserved byte-for-byte, which local
 *   development and the e2e CI workflow (android-e2e.yml) depend on.
 *   All four or nothing; partial properties are never written.
 *
 * Fail-closed secret-PRESENCE checks live in the release workflow and the
 * release-verification script, not here — this plugin never guesses and
 * never fails a build over missing env.
 *
 * Secret VALUES are never logged or echoed by this plugin. They travel only
 * into the generated, gitignored, ephemeral android/ tree; neither
 * gradle.properties nor the keystore ever enters the repository.
 *
 * Idempotent: `expo prebuild --clean` regenerates android/ from the template
 * each run, but the mods are also insertion-safe over an already-modified
 * tree (no duplicated properties, no duplicated block).
 */
// The `.js` suffix is load-bearing: `expo` has no exports map, and an
// extensionless import fails under Node 24 type-stripping with
// ERR_MODULE_NOT_FOUND, while `expo/config-plugins.js` resolves everywhere.
import type { ConfigPlugin } from "expo/config-plugins.js";
import { withAppBuildGradle, withGradleProperties } from "expo/config-plugins.js";

const STORE_FILE_KEY = "MYAPP_UPLOAD_STORE_FILE";
const KEY_ALIAS_KEY = "MYAPP_UPLOAD_KEY_ALIAS";
const STORE_PASSWORD_KEY = "MYAPP_UPLOAD_STORE_PASSWORD";
const KEY_PASSWORD_KEY = "MYAPP_UPLOAD_KEY_PASSWORD";

/**
 * Sentry proving the release signing block was already injected — used for
 * the insertion-safe idempotency check on android/app/build.gradle.
 */
const RELEASE_SIGNING_SENTRY = "if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE'))";

/**
 * The documented Expo/RN upload-signing block. The hasProperty guard keeps
 * the block inert when the MYAPP_UPLOAD_* gradle properties are absent, so
 * a missing property can never crash the build with a half-configured
 * signing config.
 */
const RELEASE_SIGNING_BLOCK = `        release {
            // KISOK upload signing — injected by plugins/with-android-release-signing.ts.
            if (project.hasProperty('MYAPP_UPLOAD_STORE_FILE')) {
                storeFile file(MYAPP_UPLOAD_STORE_FILE)
                storePassword MYAPP_UPLOAD_STORE_PASSWORD
                keyAlias MYAPP_UPLOAD_KEY_ALIAS
                keyPassword MYAPP_UPLOAD_KEY_PASSWORD
            }
        }
`;

interface UploadSigningEnv {
  storeFile: string;
  keyAlias: string;
  storePassword: string;
  keyPassword: string;
}

/**
 * Read the MYAPP_UPLOAD_* env vars at prebuild time. All four or nothing:
 * a partial set is treated as absent (fail closed), so the plugin never
 * writes partial signing properties. Values are returned only — they are
 * never logged or echoed. (Static member access on process.env is required
 * by the expo/no-dynamic-env-var lint rule; the `*_KEY` constants above are
 * the gradle.properties keys, not env access.)
 */
function readUploadSigningEnv(): UploadSigningEnv | null {
  const storeFile = process.env.MYAPP_UPLOAD_STORE_FILE;
  const keyAlias = process.env.MYAPP_UPLOAD_KEY_ALIAS;
  const storePassword = process.env.MYAPP_UPLOAD_STORE_PASSWORD;
  const keyPassword = process.env.MYAPP_UPLOAD_KEY_PASSWORD;
  if (!storeFile || !keyAlias || !storePassword || !keyPassword) {
    return null;
  }
  return { storeFile, keyAlias, storePassword, keyPassword };
}

/**
 * Index of the '}' matching the '{' at openBrace, or -1. Safe for the gradle
 * sections this plugin touches: none of their string literals or comments
 * contain braces.
 */
function findMatchingBrace(contents: string, openBrace: number): number {
  let depth = 0;
  for (let i = openBrace; i < contents.length; i++) {
    if (contents[i] === "{") {
      depth += 1;
    } else if (contents[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        return i;
      }
    }
  }
  return -1;
}

function fail(reason: string): never {
  throw new Error(
    `with-android-release-signing: ${reason} The Expo template layout changed; this plugin needs updating.`,
  );
}

/**
 * Insert the guarded `signingConfigs.release` block at the end of the
 * template's `signingConfigs` block. Idempotent: skips when the sentry is
 * already present.
 */
function insertReleaseSigningConfig(contents: string): string {
  if (contents.includes(RELEASE_SIGNING_SENTRY)) {
    return contents;
  }
  const opening = /^\s*signingConfigs\s*\{/m.exec(contents);
  if (!opening) {
    fail("expected a `signingConfigs {` block in android/app/build.gradle.");
  }
  const openBrace = opening.index + opening[0].length - 1;
  const closeBrace = findMatchingBrace(contents, openBrace);
  if (closeBrace < 0) {
    fail("could not match the `signingConfigs` block's closing brace.");
  }
  // Insert at the start of the closing brace's line, keeping the block
  // aligned with the template's `debug` config.
  const closingLineStart = contents.lastIndexOf("\n", closeBrace) + 1;
  return (
    contents.slice(0, closingLineStart) + RELEASE_SIGNING_BLOCK + contents.slice(closingLineStart)
  );
}

/**
 * Point buildTypes.release's signingConfig at the upload signing config
 * (the template default is the debug-signed release). Scoped by brace
 * matching so the `debug` build type's signingConfig is never touched.
 * Idempotent: skips when already pointing at signingConfigs.release.
 */
function pointReleaseBuildTypeAtUploadSigning(contents: string): string {
  const buildTypesOpening = /^\s*buildTypes\s*\{/m.exec(contents);
  if (!buildTypesOpening) {
    fail("expected a `buildTypes {` block in android/app/build.gradle.");
  }
  const buildTypesOpen = buildTypesOpening.index + buildTypesOpening[0].length - 1;
  const buildTypesClose = findMatchingBrace(contents, buildTypesOpen);
  if (buildTypesClose < 0) {
    fail("could not match the `buildTypes` block's closing brace.");
  }
  const buildTypes = contents.slice(buildTypesOpen, buildTypesClose + 1);

  const releaseOpening = /^\s*release\s*\{/m.exec(buildTypes);
  if (!releaseOpening) {
    fail("expected a `release {` build type inside buildTypes.");
  }
  const releaseOpen = releaseOpening.index + releaseOpening[0].length - 1;
  const releaseClose = findMatchingBrace(buildTypes, releaseOpen);
  if (releaseClose < 0) {
    fail("could not match the `release` build type's closing brace.");
  }
  const releaseBlock = buildTypes.slice(releaseOpen, releaseClose + 1);

  if (releaseBlock.includes("signingConfig signingConfigs.release")) {
    return contents;
  }
  if (!releaseBlock.includes("signingConfig signingConfigs.debug")) {
    fail("expected the template's debug-signed `release` build type default.");
  }
  const updatedRelease = releaseBlock.replace(
    "signingConfig signingConfigs.debug",
    "signingConfig signingConfigs.release",
  );
  const updatedBuildTypes =
    buildTypes.slice(0, releaseOpen) + updatedRelease + buildTypes.slice(releaseClose + 1);
  return (
    contents.slice(0, buildTypesOpen) + updatedBuildTypes + contents.slice(buildTypesClose + 1)
  );
}

/** Write the four MYAPP_UPLOAD_* entries into android/gradle.properties. */
const withUploadSigningProperties: ConfigPlugin<UploadSigningEnv> = (config, signing) => {
  return withGradleProperties(config, (config) => {
    const props = config.modResults;
    const entries: [string, string][] = [
      [STORE_FILE_KEY, signing.storeFile],
      [KEY_ALIAS_KEY, signing.keyAlias],
      [STORE_PASSWORD_KEY, signing.storePassword],
      [KEY_PASSWORD_KEY, signing.keyPassword],
    ];
    const alreadyInjected = props.some(
      (prop) => prop.type === "property" && prop.key === STORE_FILE_KEY,
    );
    if (!alreadyInjected) {
      props.push({
        type: "comment",
        value:
          "KISOK release upload signing — injected by plugins/with-android-release-signing.ts at prebuild time. The generated android/ tree is gitignored and never committed.",
      });
    }
    for (const [key, value] of entries) {
      const existing = props.find((prop) => prop.type === "property" && prop.key === key);
      if (existing && existing.type === "property") {
        existing.value = value;
      } else {
        props.push({ type: "property", key, value });
      }
    }
    return config;
  });
};

/** Add the guarded signingConfigs.release block to android/app/build.gradle. */
const withUploadSigningBuildGradle: ConfigPlugin = (config) => {
  return withAppBuildGradle(config, (config) => {
    config.modResults.contents = insertReleaseSigningConfig(config.modResults.contents);
    config.modResults.contents = pointReleaseBuildTypeAtUploadSigning(config.modResults.contents);
    return config;
  });
};

/**
 * Env-guarded Android release-signing plugin. Without ALL FOUR
 * MYAPP_UPLOAD_* env vars it makes NO native modification — local dev and
 * e2e CI keep the Expo template's debug-signed release default, and the
 * fail-closed presence checks live in the release workflow, not here.
 */
const withAndroidReleaseSigning: ConfigPlugin = (config) => {
  const signing = readUploadSigningEnv();
  if (!signing) {
    return config;
  }
  config = withUploadSigningProperties(config, signing);
  config = withUploadSigningBuildGradle(config);
  return config;
};

export default withAndroidReleaseSigning;
