/**
 * Declares KISOK's Android Enterprise MANAGED CONFIGURATION schema.
 *
 * The native `android/` tree is generated by `expo prebuild` and is not
 * committed, so every native change must flow through a config plugin. This
 * one adds the two pieces Android documents for managed configurations:
 *
 *  1. `<meta-data android:name="android.content.APP_RESTRICTIONS"
 *     android:resource="@xml/kiosk_restrictions"/>` inside `<application>`;
 *  2. `res/xml/kiosk_restrictions.xml`, the schema itself, plus the
 *     `res/values` strings it references.
 *
 * Both follow https://developer.android.com/work/managed-configurations and
 * the official Android Enterprise sample:
 *
 *   https://github.com/android/enterprise-samples — `ManagedConfigurations`
 *   Copyright 2014 The Android Open Source Project, licensed under the
 *   Apache License, Version 2.0. The manifest meta-data element and the
 *   `<restrictions>`/`<restriction>` element shape below are adapted from it.
 *
 * What this plugin does NOT do is as important: it sets no lock-task
 * attribute, declares no device-admin receiver, and requests no policy
 * permission. Android and ManageEngine own device lockdown; KISOK only reads
 * one value to know which kind of tablet it is on.
 *
 * `android:description` accepts a string RESOURCE reference only — a literal
 * fails `:app:processDebugResources` — which is why the display strings live
 * in `res/values` and are referenced with `@string/`, exactly as the sample
 * does for both title and description.
 */
// The `.js` suffix is load-bearing: `expo` has no exports map, so an
// extensionless specifier fails under Node's type-stripping loader with
// ERR_MODULE_NOT_FOUND, while `expo/config-plugins.js` resolves everywhere.
import configPlugins, {
  withAndroidManifest,
  withDangerousMod,
  type ConfigPlugin,
} from "expo/config-plugins.js";
import fs from "node:fs";
import path from "node:path";

// `AndroidConfig` is a namespace object that Node's CJS named-export detection
// does not see, so it comes off the default export rather than a named import.
const { AndroidConfig } = configPlugins;

/** `RestrictionsManager.META_DATA_APP_RESTRICTIONS`. */
const META_DATA_NAME = "android.content.APP_RESTRICTIONS";
const RESTRICTIONS_RESOURCE = "kiosk_restrictions";

/**
 * ONE descriptive restriction. Parsing remains:
 *
 *   ABSENT                     -> `standard`
 *   exactly "customer_kiosk"   -> `customer-kiosk`
 *   ANY other present value    -> `unknown`
 *
 * Device classification does not determine account access. Both tablet roles
 * can use their experience regardless of this value or native read status.
 *
 * The native module maps a present null to "" so an explicitly cleared value
 * stays present to JS. The choice field offers the one recognized kiosk value.
 *
 * No `android:defaultValue` and no "not configured" entry: omitting a default
 * preserves the unset reading. Any default would be a real value, changing that
 * classification. The console decides how it draws the unset dropdown; see
 * `features/device-mode/docs/mdm-operations.md` → "Initial state in the console".
 */
export const RESTRICTIONS_XML = `<?xml version="1.0" encoding="utf-8"?>
<restrictions xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- Set by the MDM on the store's Customer Kiosk tablet. The ONLY value
         KISOK treats as a kiosk is "customer_kiosk". Leaving the key UNSET is
         what an ordinary employee tablet looks like. Any OTHER present value
         is read as unknown, not as an ordinary tablet: only an MDM can set
         this key. Device classification never prevents an authenticated
         Preparation or Customer account from using its experience. -->
    <restriction
        android:key="kiosk_device_role"
        android:restrictionType="choice"
        android:entries="@array/kiosk_device_role_entries"
        android:entryValues="@array/kiosk_device_role_values"
        android:title="@string/kiosk_device_role_title"
        android:description="@string/kiosk_device_role_description" />
</restrictions>
`;

export const STRINGS_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="kiosk_device_role_title">Kiosk device role</string>
    <string name="kiosk_device_role_description">Choose Customer kiosk tablet on the store Customer Kiosk tablet only. Leave this not configured on employee tablets.</string>

    <!-- The label an administrator sees, and the value the app actually reads.
         The two arrays are positional: entries[i] is shown for values[i]. -->
    <string-array name="kiosk_device_role_entries">
        <item>Customer kiosk tablet</item>
    </string-array>
    <string-array name="kiosk_device_role_values">
        <item>customer_kiosk</item>
    </string-array>
</resources>
`;

/** Declare the managed-configuration schema via `<application>` meta-data. */
const withAppRestrictionsMetaData: ConfigPlugin = (config) =>
  withAndroidManifest(config, (config) => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults);
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      application,
      META_DATA_NAME,
      `@xml/${RESTRICTIONS_RESOURCE}`,
      "resource",
    );
    return config;
  });

/** Write the restrictions schema and its display strings into the generated tree. */
const withRestrictionsResources: ConfigPlugin = (config) =>
  withDangerousMod(config, [
    "android",
    (config) => {
      const resRoot = path.join(config.modRequest.platformProjectRoot, "app/src/main/res");
      const xmlDir = path.join(resRoot, "xml");
      const valuesDir = path.join(resRoot, "values");

      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(path.join(xmlDir, `${RESTRICTIONS_RESOURCE}.xml`), RESTRICTIONS_XML);
      fs.mkdirSync(valuesDir, { recursive: true });
      fs.writeFileSync(path.join(valuesDir, "kiosk_device_role_strings.xml"), STRINGS_XML);

      return config;
    },
  ]);

const withManagedConfiguration: ConfigPlugin = (config) =>
  withRestrictionsResources(withAppRestrictionsMetaData(config));

export default withManagedConfiguration;
