/**
 * KISOK kiosk-policy local Expo module — Android config plugin.
 *
 * Structural, deterministic, idempotent native configuration for CNG (the
 * android/ tree is regenerated by `expo prebuild` and never committed, so all
 * native configuration must flow through here):
 *
 *  1. `<meta-data android:name="android.content.APP_RESTRICTIONS"
 *     android:resource="@xml/kiosk_restrictions"/>` inside `<application>` —
 *     declares the managed-configurations schema so an Android Enterprise
 *     MDM (ManageEngine) can push app restrictions to this app.
 *  2. `android/app/src/main/res/xml/kiosk_restrictions.xml` — the schema
 *     itself (three restrictions; see the XML below).
 *  3. `android:lockTaskMode="if_whitelisted"` on the main activity — the
 *     one-APK dual-role mechanism: the system locks the app into real lock
 *     task mode only when a DPC has allowlisted this package (store kiosk
 *     tablets), and behaves as a normal activity everywhere else (employee
 *     tablets). The app never calls startLockTask/stopLockTask itself.
 *
 * Meta-data name and restriction types follow current Android documentation:
 * https://developer.android.com/work/managed-configurations (the constant is
 * RestrictionsManager.META_DATA_APP_RESTRICTIONS = "android.content.APP_RESTRICTIONS").
 * The lock-task attribute: https://developer.android.com/guide/topics/manifest/activity-element
 */
const { withAndroidManifest, withDangerousMod, AndroidConfig } = require("expo/config-plugins");

const RESTRICTIONS_XML = `<?xml version="1.0" encoding="utf-8"?>
<restrictions xmlns:android="http://schemas.android.com/apk/res/android">

    <!-- MDM-set device role. The app treats ONLY the explicit value
         "customer_kiosk" as a kiosk device (fail closed: missing, pending or
         invalid values behave as "standard"). -->
    <restriction
        android:key="kiosk_device_role"
        android:restrictionType="string"
        android:title="Kiosk device role"
        android:description="Set by the MDM. Use customer_kiosk on store Customer tablets; anything else behaves as a normal device." />

    <!-- Store-staff maintenance unlock credential, delivered by the MDM.
         Never a Supabase credential; never logged or persisted by the app. -->
    <restriction
        android:key="maintenance_unlock_code"
        android:restrictionType="string"
        android:title="Maintenance unlock code" />

    <!-- Optional unlock lifetime in seconds; the app clamps 15..600. -->
    <restriction
        android:key="maintenance_unlock_timeout_seconds"
        android:restrictionType="integer"
        android:title="Maintenance unlock timeout (seconds)" />
</restrictions>
`;

const META_DATA_NAME = "android.content.APP_RESTRICTIONS";
const META_DATA_RESOURCE = "@xml/kiosk_restrictions";
const LOCK_TASK_MODE_ATTRIBUTE = "android:lockTaskMode";
const LOCK_TASK_MODE_VALUE = "if_whitelisted";

/** Set android:lockTaskMode="if_whitelisted" on the .MainActivity element. */
function withLockTaskMode(config) {
  return withAndroidManifest(config, (config) => {
    const androidManifest = config.modResults;
    const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(androidManifest);
    mainActivity.$[LOCK_TASK_MODE_ATTRIBUTE] = LOCK_TASK_MODE_VALUE;
    return config;
  });
}

/** Declare the managed-configurations schema via application meta-data. */
function withAppRestrictionsMetaData(config) {
  return withAndroidManifest(config, (config) => {
    const androidManifest = config.modResults;
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
    AndroidConfig.Manifest.addMetaDataItemToMainApplication(
      application,
      META_DATA_NAME,
      META_DATA_RESOURCE,
      "resource",
    );
    return config;
  });
}

/** Write res/xml/kiosk_restrictions.xml into the generated android project. */
function withRestrictionsXmlResource(config) {
  return withDangerousMod(config, [
    "android",
    (config) => {
      const resDir = `${config.modRequest.platformProjectRoot}/app/src/main/res/xml`;
      const fs = require("node:fs");
      fs.mkdirSync(resDir, { recursive: true });
      fs.writeFileSync(`${resDir}/kiosk_restrictions.xml`, RESTRICTIONS_XML);
      return config;
    },
  ]);
}

module.exports = function withKioskPolicy(config) {
  config = withAppRestrictionsMetaData(config);
  config = withLockTaskMode(config);
  config = withRestrictionsXmlResource(config);
  return config;
};
